version: '3.8'

# LOCAL DEVELOPMENT ONLY
# For team collaboration, use cloud database (Supabase) with DATABASE_URL in .env
# This PostgreSQL is for local testing without internet dependency

services:
  postgres:
    image: postgres:15-alpine
    container_name: reviews-postgres
    environment:
      POSTGRES_USER: reviewuser
      POSTGRES_PASSWORD: reviewpass123
      POSTGRES_DB: reviews
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reviewuser -d reviews"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
